server:
  port : 8088

spring:
  application:
    name: neo-phone-number-api
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    com.neotech: DEBUG
    org.springframework.:
      root: DEBUG
      web: DEBUG
    org.hibernate: ERROR
