INSERT INTO neo.country_phone_codes (id, country, code) VALUES (1, 'Abkhazia', 7840);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (2, 'Abkhazia', 7940);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (3, 'Afghanistan', 93);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (4, 'Åland', 35818);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (5, 'Albania', 355);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (6, 'Algeria', 213);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (7, 'American Samoa', 1684);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (8, 'Andorra', 376);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (9, 'Angola', 244);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (10, 'Anguilla', 1264);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (11, 'Antigua and Barbuda', 1268);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (12, 'Argentina', 54);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (13, 'Armenia', 374);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (14, 'Aruba', 297);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (15, 'Ascension', 247);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (16, 'Australia', 61);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (17, 'Austria', 43);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (18, 'Azerbaijan', 994);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (20, 'Bahrain', 973);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (21, 'Bangladesh', 880);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (23, 'Belarus', 375);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (24, 'Belgium', 32);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (25, 'Belize', 501);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (26, 'Benin', 229);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (27, 'Bermuda', 1441);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (28, 'Bhutan', 975);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (29, 'Bolivia', 591);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (31, 'Bosnia and Herzegovina', 387);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (32, 'Botswana', 267);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (33, 'Brazil', 55);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (34, 'British Indian Ocean Territory (Diego Garcia)', 246);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (35, 'British Virgin Islands', 1284);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (36, 'Brunei Darussalam', 673);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (37, 'Bulgaria', 359);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (38, 'Burkina Faso', 226);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (39, 'Burundi', 257);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (40, 'Cape Verde', 238);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (41, 'Cambodia', 855);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (42, 'Cameroon', 237);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (43, 'Canada', 1);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (44, 'Caribbean Netherlands', 5993);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (45, 'Caribbean Netherlands', 5994);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (46, 'Caribbean Netherlands', 5997);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (47, 'Cayman Islands', 1345);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (48, 'Central African Republic', 236);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (49, 'Chad', 235);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (50, 'Chile', 56);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (51, 'China', 86);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (52, 'Christmas Island', 6189164);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (53, 'Cocos (Keeling) Islands', 6189162);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (54, 'Colombia', 57);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (55, 'Comoros', 269);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (56, 'Congo', 242);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (57, 'Congo, Democratic Republic of the', 243);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (58, 'Cook Islands', 682);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (59, 'Costa Rica', 506);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (60, 'Ivory Coast (Côte dIvoire)', 225);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (61, 'Croatia', 385);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (62, 'Cuba', 53);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (63, 'Curaçao', 5999);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (64, 'Cyprus', 357);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (65, 'Czech Republic', 420);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (66, 'Denmark', 45);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (67, 'Djibouti', 253);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (69, 'Dominican Republic', 1809);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (70, 'Dominican Republic', 1829);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (71, 'Dominican Republic', 1849);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (72, 'Easter Island', 56);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (73, 'Ecuador', 593);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (74, 'Egypt', 20);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (75, 'El Salvador', 503);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (76, 'Equatorial Guinea', 240);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (77, 'Eritrea', 291);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (78, 'Estonia', 372);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (79, 'Eswatini', 268);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (80, 'Ethiopia', 251);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (81, 'Falkland Islands', 500);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (82, 'Faroe Islands', 298);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (83, 'Fiji', 679);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (84, 'Finland', 358);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (85, 'France', 33);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (87, 'French Guiana', 594);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (88, 'French Polynesia', 689);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (89, 'Gabon', 241);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (90, 'Gambia', 220);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (91, 'Georgia', 995);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (92, 'Germany', 49);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (93, 'Ghana', 233);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (94, 'Gibraltar', 350);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (95, 'Greece', 30);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (96, 'Greenland', 299);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (98, 'Guadeloupe', 590);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (100, 'Guatemala', 502);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (101, 'Guernsey', 441481);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (102, 'Guernsey', 447781);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (103, 'Guernsey', 447839);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (104, 'Guernsey', 447911);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (105, 'Guinea', 224);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (106, 'Guinea-Bissau', 245);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (107, 'Guyana', 592);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (108, 'Haiti', 509);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (109, 'Honduras', 504);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (110, 'Hong Kong', 852);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (111, 'Hungary', 36);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (112, 'Iceland', 354);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (113, 'India', 91);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (114, 'Indonesia', 62);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (115, 'Iran', 98);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (116, 'Iraq', 964);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (117, 'Ireland', 353);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (118, 'Isle of Man', 441624);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (119, 'Isle of Man', 447524);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (120, 'Isle of Man', 447624);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (121, 'Isle of Man', 447924);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (122, 'Israel', 972);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (123, 'Italy', 39);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (124, 'Jamaica', 1658);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (125, 'Jamaica', 1876);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (126, 'Jan Mayen', 4779);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (127, 'Japan', 81);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (128, 'Jersey', 441534);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (129, 'Jordan', 962);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (130, 'Kazakhstan', 76);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (131, 'Kazakhstan', 77);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (132, 'Kenya', 254);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (133, 'Kiribati', 686);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (134, 'Korea, North', 850);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (135, 'Korea, South', 82);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (136, 'Kosovo', 383);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (137, 'Kuwait', 965);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (138, 'Kyrgyzstan', 996);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (139, 'Laos', 856);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (140, 'Latvia', 371);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (141, 'Lebanon', 961);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (142, 'Lesotho', 266);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (143, 'Liberia', 231);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (144, 'Libya', 218);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (145, 'Liechtenstein', 423);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (146, 'Lithuania', 370);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (147, 'Luxembourg', 352);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (148, 'Macau', 853);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (149, 'Madagascar', 261);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (150, 'Malawi', 265);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (151, 'Malaysia', 60);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (152, 'Maldives', 960);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (153, 'Mali', 223);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (154, 'Malta', 356);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (155, 'Marshall Islands', 692);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (156, 'Martinique', 596);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (157, 'Mauritania', 222);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (158, 'Mauritius', 230);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (160, 'Mexico', 52);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (161, 'Micronesia, Federated States of', 691);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (162, 'Moldova', 373);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (163, 'Monaco', 377);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (164, 'Mongolia', 976);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (165, 'Montenegro', 382);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (166, 'Montserrat', 1664);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (167, 'Morocco', 212);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (168, 'Mozambique', 258);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (169, 'Myanmar', 95);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (170, 'Namibia', 264);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (171, 'Nauru', 674);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (172, 'Nepal', 977);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (173, 'Netherlands', 31);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (175, 'New Caledonia', 687);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (176, 'New Zealand', 64);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (177, 'Nicaragua', 505);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (178, 'Niger', 227);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (179, 'Nigeria', 234);
INSERT INTO neo.country_phone_codes (id, country, code) VALUES (180, 'Niue', 683);